#!/bin/bash
#
#kolmnurk
# ülemine pool
for((r=1; r<4; r++))
do
	# veerud - tärnid
	# tärnide arv algab 1-st
	# Igal veerul tärnide arv ei tohi ületada rea numbri
	for((t=1; t<$(($r+1)); t++))
	do
	echo -n "* "
	done
	echo # reavahetus

done
#alumine pool
for((r=4; r>0; r--))
do
	for((t=1; t<$(($r+1)); t++))
do
echo -n "* "
done
echo
done
