#!/bin/bash
# ip järgi arvuti kontrollimine
for ip in 172.23.13.{20..50}
do
	# teatamen antud ip pingi
ping -c 1 $ip > /dev/null # väljund kustutatud
# kontroll
if [ $? -eq 0 ]; then
# kui $? on 0 - kõik korras
echo "$ip - ok"
# muidu
else
echo "$ip -not"
fi
done

