#!/bin/bash
#
# arvu kontoll - positiivne või negatiivne
echo -n "sisesta arv: "
read arv
# nüüd kontrollib, kas arv on positiivne
# sel juhul arv peab olema suurem kui 0
if [ $arv -gt 0 ]
then
	# jah, arv on suurem kui 0 - positiivne
	echo "$arv on positiivne"
# kui ei ole suurem kui 0 - negatiivne
else
	echo "$arv on negatiivne"
# if lause tuleb korralikult lõpetada
fi
